### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'

### ISSUE THREAD

**Issue by rperdon** [Zeqiang-Lai/DragGAN#116]
Cuda 11.8 installed 

No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
Traceback (most recent call last):
File "C:\Users\Slade\Downloads\draggan_install\DragGAN\visualizer_drag.py", line 403, in
main()
File "C:\Python\Lib\site-packages\click\core.py", line 1157, in call
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python\Lib\site-packages\click\core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "C:\Python\Lib\site-packages\click\core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python\Lib\site-packages\click\core.py", line 783, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Slade\Downloads\draggan_install\DragGAN\visualizer_drag.py", line 397, in main
viz.draw_frame()
File "C:\Users\Slade\Downloads\draggan_install\DragGAN\visualizer_drag.py", line 168, in draw_frame
self._async_renderer.set_args(**self.args)
File "C:\Users\Slade\Downloads\draggan_install\DragGAN\visualizer_drag.py", line 295, in set_args
self._set_args_sync(**args)
File "C:\Users\Slade\Downloads\draggan_install\DragGAN\visualizer_drag.py", line 312, in _set_args_sync
self._renderer_obj = renderer.Renderer()
^^^^^^^^^^^^^^^^^^^
File "C:\Users\Slade\Downloads\draggan_install\DragGAN\viz\renderer.py", line 80, in init
self._start_event = torch.cuda.Event(enable_timing=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python\Lib\site-packages\torch\cuda\streams.py", line 164, in new
return super(Event, cls).new(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python\Lib\site-packages\torch\cuda_utils.py", line 46, in err_fn
raise RuntimeError(
RuntimeError: Tried to instantiate dummy base class Event

**Comment by rperdon** [comment]
The fix:
pip install torch==2.0.1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118

**Comment by rperdon** [comment]
The fix:
pip install torch==2.0.1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
