### ISSUE TITLE
python -m draggon.web, when add point, it failed.

### ISSUE THREAD

**Issue by hitzhangjie** [Zeqiang-Lai/DragGAN#120]
hi, bro, I spend 1 night to solve the problem, I solved the cuda problem, well it now still fails for some reason.

Please help, how should I fix this?

My environment is as following:
1. Windows 11
2. Visual Studio 2022 Community (C++ core features installed), it the compiler searchpath added to script
3. cuda toolkit 11.7 installed and environment variable configured,
4. my GPU is rtx 4090.

```
(draggan) D:\AI\DragGAN>python -m draggan.web
Loading networks from "C:\Users\Administrator\draggan\checkpoints-pkl\ada/afhqcat.pkl"...
Registering hook for: b256
Setting up PyTorch plugin "bias_act_plugin"... Done.
Registering hook for: b256
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
Successfully loaded, starting gradio demo
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Task exception was never retrieved
future: <Task finished coro=<Queue.process_events() done, defined at C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['ada/afhqdog.pk...ion_hash': '850fg6f9lb'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing>
Traceback (most recent call last):
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['ada/afhqdog.pk...ion_hash': '850fg6f9lb'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
Task exception was never retrieved
future: <Task finished coro=<Queue.process_events() done, defined at C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, None, 20,...ion_hash': '850fg6f9lb'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing>
Traceback (most recent call last):
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, None, 20,...ion_hash': '850fg6f9lb'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
Task exception was never retrieved
future: <Task finished coro=<Queue.process_events() done, defined at C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['data:image/png...on_hash': '4x236yvyodl'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing>
Traceback (most recent call last):
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['data:image/png...on_hash': '4x236yvyodl'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
Task exception was never retrieved
future: <Task finished coro=<Queue.process_events() done, defined at C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, None, 20,...on_hash': '4x236yvyodl'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing>
Traceback (most recent call last):
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, None, 20,...on_hash': '4x236yvyodl'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
Task exception was never retrieved
future: <Task finished coro=<Queue.process_events() done, defined at C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['data:image/png...on_hash': 'u9igcpfo8ud'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing>
Traceback (most recent call last):
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['data:image/png...on_hash': 'u9igcpfo8ud'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
Task exception was never retrieved
future: <Task finished coro=<Queue.process_events() done, defined at C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['data:image/png...on_hash': '2eiyecluxrq'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing>
Traceback (most recent call last):
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['data:image/png...on_hash': '2eiyecluxrq'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
Task exception was never retrieved
future: <Task finished coro=<Queue.process_events() done, defined at C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, None, 20,...on_hash': '2eiyecluxrq'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing>
Traceback (most recent call last):
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "C:\Users\Administrator\miniconda3\envs\draggan\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, None, 20,...on_hash': '2eiyecluxrq'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
```

**Comment by p1utoze** [comment]
hey @hitzhangjie I have the same issue. Were you able to solve it?

**Comment by hauelp284** [comment]
Hi, I am having the same issue. Has anyone found a fix? I don't understand what the error is. Thanks!
