### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'img_resolution'

### ISSUE THREAD

**Issue by plx-bigdata** [Zeqiang-Lai/DragGAN#122]
when i run **python visualizer_drag_gradio.py**
report issue: **AttributeError: 'dict' object has no attribute 'img_resolution**
how do i solve this issue?

**Comment by wangwenqiao666** [comment]
I have the same problem

Traceback (most recent call last):
  File "/data/DragGAN/visualizer_drag_gradio.py", line 205, in <module>
    global_state = init_images(global_state)
  File "/data/DragGAN/visualizer_drag_gradio.py", line 75, in init_images
    state['renderer'].init_network(
  File "/data/DragGAN/viz/renderer.py", line 224, in init_network
    res.img_resolution = G.img_resolution
AttributeError: 'dict' object has no attribute 'img_resolution'

![image](https://github.com/OpenGVLab/DragGAN/assets/55267900/42c01454-9f83-4561-911a-03911edf6155)

**Comment by woshixty** [comment]
i also have this problem

**Comment by liuquanhao** [comment]
me too.

**Comment by timchenxiaoyu** [comment]
me too

**Comment by cyhhhhhhit** [comment]
i solved it by add: `state['generator_params'] = dnnlib.EasyDict()` before `state['renderer'].init_network`

**Comment by BalaMurugan171103** [comment]
> I have the same problem
> 
> Traceback (most recent call last): File "/data/DragGAN/visualizer_drag_gradio.py", line 205, in global_state = init_images(global_state) File "/data/DragGAN/visualizer_drag_gradio.py", line 75, in init_images state['renderer'].init_network( File "/data/DragGAN/viz/renderer.py", line 224, in init_network res.img_resolution = G.img_resolution AttributeError: 'dict' object has no attribute 'img_resolution'
> 
> ![image](https://private-user-images.githubusercontent.com/55267900/283108660-42c01454-9f83-4561-911a-03911edf6155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzc3NzMsIm5iZiI6MTcxNDAzNzQ3MywicGF0aCI6Ii81NTI2NzkwMC8yODMxMDg2NjAtNDJjMDE0NTQtOWY4My00NTYxLTkxMWEtMDM5MTFlZGY2MTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA5MzExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyOGY1ZmMyZmMwZGIzZjdjNGZjODI3ZmNhZDdiMTY0YzExYWU2YzJlNzkwOTA4ZGQ1OGIwODdhZGI0ZTU1NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T6CtCimLyx4_X5QUTdX1Gnwtar0k8-6grEa3PsWj53c)

did you resolve this issue

**Comment by wangwenqiao666** [comment]
好像解决了，当时更新代码就好了

**Comment by Harry19s** [comment]
> when i run **python visualizer_drag_gradio.py**
> report issue: **AttributeError: 'dict' object has no attribute 'img_resolution**
> how do i solve this issue?

I don't know why but I solved this issue by
```python
pip install gradio==3.36.1
```

this was also useful for pydantic error
