### ISSUE TITLE
TypeError: Image.__init__() got an unexpected keyword argument 'source'

### ISSUE THREAD

**Issue by h21k** [Zeqiang-Lai/DragGAN#124]
Hi all got the following error on Colab:

File under cache_dir (./checkpoints):
['stylegan2_elephants_512_pytorch.pkl', 'stylegan2-afhqcat-512x512.pkl', 'stylegan2-cat-config-f.pkl', 'stylegan2_lions_512_pytorch.pkl', 'stylegan2_dogs_1024_pytorch.pkl', 'stylegan2_horses_256_pytorch.pkl', 'stylegan2-car-config-f.pkl', 'stylegan2-ffhq-512x512.pkl']
Valid checkpoint file:
{'stylegan2_elephants_512_pytorch': './checkpoints/stylegan2_elephants_512_pytorch.pkl', 'stylegan2-afhqcat-512x512': './checkpoints/stylegan2-afhqcat-512x512.pkl', 'stylegan2-cat-config-f': './checkpoints/stylegan2-cat-config-f.pkl', 'stylegan2_lions_512_pytorch': './checkpoints/stylegan2_lions_512_pytorch.pkl', 'stylegan2_dogs_1024_pytorch': './checkpoints/stylegan2_dogs_1024_pytorch.pkl', 'stylegan2_horses_256_pytorch': './checkpoints/stylegan2_horses_256_pytorch.pkl', 'stylegan2-car-config-f': './checkpoints/stylegan2-car-config-f.pkl', 'stylegan2-ffhq-512x512': './checkpoints/stylegan2-ffhq-512x512.pkl'}
Loading "./checkpoints/stylegan2_lions_512_pytorch.pkl"... Done.
()
{'z_dim': 512, 'c_dim': 0, 'w_dim': 512, 'img_resolution': 512, 'img_channels': 3, 'mapping_kwargs': {'num_layers': 8, 'embed_features': None, 'layer_features': None, 'activation': 'lrelu', 'lr_multiplier': 0.01, 'w_avg_beta': 0.995}, 'synthesis_kwargs': {'channel_base': 32768, 'channel_max': 512, 'num_fp16_res': 0, 'conv_clamp': None, 'architecture': 'skip', 'resample_filter': [1, 3, 3, 1], 'use_noise': True, 'activation': 'lrelu'}}
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
Traceback (most recent call last):
  File "/content/DragGAN/visualizer_drag_gradio.py", line 308, in <module>
    form_image = ImageMask(
  File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 159, in wrapper
    return fn(self, **kwargs)
  File "/content/DragGAN/gradio_utils/utils.py", line 14, in __init__
    super().__init__(source="upload",
  File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 159, in wrapper
    return fn(self, **kwargs)
TypeError: Image.__init__() got an unexpected keyword argument 'source'

**Comment by liuzz07** [comment]
gradio incompatible version issue, run `pip install gradio==3.50.2` to fix
