### ISSUE TITLE
Requirements Error

### ISSUE THREAD

**Issue by dylanjrae** [Zeqiang-Lai/DragGAN#13]
Running `python gradio_app.py` I get the following stack trace, any suggestions?

```
Traceback (most recent call last):
  File "/Users/dylanrae/Documents/GitHub/DragGAN/gradio_app.py", line 9, in <module>
    from drag_gan import drag_gan, stylegan2
  File "/Users/dylanrae/Documents/GitHub/DragGAN/drag_gan.py", line 9, in <module>
    from torchvision import utils
  File "/Users/dylanrae/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/Users/dylanrae/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel
  File "/Users/dylanrae/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torchvision/datasets/_optical_flow.py", line 13, in <module>
    from .utils import _read_pfm, verify_str_arg
  File "/Users/dylanrae/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torchvision/datasets/utils.py", line 6, in <module>
    import lzma
  File "/Users/dylanrae/.pyenv/versions/3.10.6/lib/python3.10/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
```

**Comment by Zeqiang-Lai** [comment]
I personally recommend to use Conda to create environment. For you problem, these links might help

https://stackoverflow.com/questions/59690698/modulenotfounderror-no-module-named-lzma-when-building-python-using-pyenv-on

https://github.com/pytorch/vision/issues/2921

https://stackoverflow.com/questions/72698302/no-module-named-lzma
