### ISSUE TITLE
RuntimeError: Ninja is required to load C++ extensions

### ISSUE THREAD

**Issue by Misterkiwi500** [Zeqiang-Lai/DragGAN#2]
Hello and I found an error, I made on google colab created on your work github and I get the error like this:

/content/DragGAN
Traceback (most recent call last):
  File "/content/DragGAN/gradio_app.py", line 3, in <module>
    from drag_gan import stylegan2, drag_gan
  File "/content/DragGAN/drag_gan.py", line 12, in <module>
    from stylegan2.model import Generator
  File "/content/DragGAN/stylegan2/model.py", line 8, in <module>
    from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d, conv2d_gradfix
  File "/content/DragGAN/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/content/DragGAN/stylegan2/op/fused_act.py", line 11, in <module>
    fused = load(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1593, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1649, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions

the question is, can you fix it? if you have fixed it then, many thanks for the conversation. thx

**Comment by Zeqiang-Lai** [comment]
Maybe you could try.

pip install ninja

**Comment by Mistermango23** [comment]
I try

**Comment by Mistermango23** [comment]
Ok it's work! Thank you
