### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by trouble-maker007** [Zeqiang-Lai/DragGAN#3]
while I select two points and press drag it
```
Traceback (most recent call last):
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/gradio/blocks.py", line 1320, in process_api
    result = await self.call_function(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/gradio/blocks.py", line 1064, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/gradio/utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/gradio/utils.py", line 507, in __anext__
    return await anyio.to_thread.run_sync(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/gradio/utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "/group/20000/ramseyhuang/DragGAN/gradio_app.py", line 39, in on_drag
    for sample2, latent, F in drag_gan(g_ema, latent, noise, F,
  File "/group/20000/ramseyhuang/DragGAN/drag_gan.py", line 189, in drag_gan
    pi, ti = handle_points[i], target_points[i]
IndexError: list index out of range
```

And my gradio page is different with the one in demo.mp4
<img width="1544" alt="image" src="https://github.com/Zeqiang-Lai/DragGAN/assets/73164596/bf31e4be-676b-4f65-ba48-c575815504bc">

**Comment by Zeqiang-Lai** [comment]
I have updated the demo. Do you still face the same issue wit this [link](https://2db7de2bdb2b26469d.gradio.live/) ?

**Comment by trouble-maker007** [comment]
@Zeqiang-Lai Thanks for the quick response, I found the problem, I need to check 'target point' before selecting the second option.

But I found a new problem that I want to make the right eye close, but it fail

**Comment by Zeqiang-Lai** [comment]
Thanks for the feedback, I also notice the problem. Maybe there are some bugs or differences of my implementation of the original one. Let me try to fix it.

**Comment by sigrace1111** [comment]
same problem

**Comment by AFindex** [comment]
same problem
