### ISSUE TITLE
DLL load failed while importing fused: The specified module could not be found.

### ISSUE THREAD

**Issue by Germin4l** [Zeqiang-Lai/DragGAN#38]
Can it work with Torch2.0 or does it use functions that aren't present in 2.0? (that is what I suspect at first glance)
I tried and I get "DLL load failed while importing fused: The specified module could not be found."

# Error: DLL load failed while importing fused: The specified module could not be found.
# # Traceback (most recent call last):
# #   File "<maya console>", line 1, in <module>
# #   File "Z:\MAYA_AI\plugin\python\drag_gan.py", line 12, in <module>
# #     from stylegan2.model import Generator
# #   File "Z:\MAYA_AI\plugin\python\stylegan2\model.py", line 8, in <module>
# #     from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d, conv2d_gradfix
# #   File "Z:\MAYA_AI\plugin\python\stylegan2\op\__init__.py", line 1, in <module>
# #     from .fused_act import FusedLeakyReLU, fused_leaky_relu
# #   File "Z:\MAYA_AI\plugin\python\stylegan2\op\fused_act.py", line 11, in <module>
# #     fused = load(
# #   File "C:\Users\pj\AppData\Roaming\Python\Python39\site-packages\torch\utils\cpp_extension.py", line 1284, in load
# #     return _jit_compile(
# #   File "C:\Users\pj\AppData\Roaming\Python\Python39\site-packages\torch\utils\cpp_extension.py", line 1535, in _jit_compile
# #     return _import_module_from_library(name, build_directory, is_python_module)
# #   File "C:\Users\pj\AppData\Roaming\Python\Python39\site-packages\torch\utils\cpp_extension.py", line 1929, in _import_module_from_library
# #     module = importlib.util.module_from_spec(spec)
# # ImportError: DLL load failed while importing fused: The specified module could not be found.

**Comment by Zeqiang-Lai** [comment]
torch2.0 should work. This is problem is caused by the stylegan cuda extension. Check this out https://github.com/Zeqiang-Lai/DragGAN/issues/12

**Comment by Germin4l** [comment]
Thank you! I'm not using Conda. Do you think there is a way to make it work without it?

**Comment by Germin4l** [comment]
By the way, I'm an animator and I think this kind of thing will be revolutionary. Thanks for implementing it.

**Comment by Zeqiang-Lai** [comment]
Yes，there are many issues similar as yours on windows，it seems some of them solve the problem without cuda by installing visual studio.

I will try to simplify the installation later this week. 

Thanks again for the attention

**Comment by Germin4l** [comment]
I figured it out. 'ninja.exe' needs to be in 'PATH' on windows, it's as simple as that.

in my case, add this to 'PATH':
C:\Users\pj\AppData\Roaming\Python\Python39\Scripts

**Comment by Germin4l** [comment]
well. now I get Cannot open include file: 'Python.h': No such file or directory
# # ninja: build stopped: subcommand failed.

Another Torch-related error.

**Comment by Germin4l** [comment]
thanks friend! It looks like it it works now.

I just get a warning that might be something or nothing, i don't know yet, but the import now works.
python\stylegan2\op\upfirdn2d.py:21: UserWarning: Fail to build torch extension, switch to native implementation
  warnings.warn(

**Comment by Zeqiang-Lai** [comment]
Do you mean you want to uninstall ninja ? If it is, I don't know if it would cause problems. What I mean is that you are likely won't meet errors about ninja anymore.

**Comment by Germin4l** [comment]
I see. I'm trying to make this work along Stable diffusion in a non-conda environment (with a custom UI) which is why it's a bit complicated.

**Comment by ATUI-TING** [comment]
I have the same problems:
`(AGE) D:\model\AGE-main>python tools/inference.py
  File "D:\model\AGE-main\.\models\stylegan2\op\fused_act.py", line 9, in <module>
    fused = load(
  File "D:\SourceCode\anaconda3\envs\AGE\lib\site-packages\torch\utils\cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "D:\SourceCode\anaconda3\envs\AGE\lib\site-packages\torch\utils\cpp_extension.py", line 1362, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\SourceCode\anaconda3\envs\AGE\lib\site-packages\torch\utils\cpp_extension.py", line 1752, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
**ImportError: DLL load failed while importing fused: The specified module could not be found.**`

The packages I installed with conda are as follows:
`# packages in environment at D:\SourceCode\anaconda3\envs\AGE:          
#                                                                       
# Name                    Version                   Build  Channel      
blas                      1.0                         mkl               
brotli                    1.0.9                h2bbff1b_7               
brotli-bin                1.0.9                h2bbff1b_7               
ca-certificates           2023.08.22           haa95532_0               
certifi                   2023.11.17       py38haa95532_0               
colorama                  0.4.6            py38haa95532_0               
cudatoolkit               11.3.1              h280eb24_10    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0               
eigen                     3.4.0                h59b6b97_0
ffmpeg                    4.2.2                he774522_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               ha860e81_0
giflib                    5.2.1                h8cc25b3_3
glib                      2.69.1               h5dc1a3c_2
gst-plugins-base          1.18.5               h9e645db_0
gstreamer                 1.18.5               hd78058f_0
hdf5                      1.12.1               h51c971a_3
icc_rt                    2022.1.0             h6049295_2
icu                       58.2                 ha925a31_3
intel-openmp              2023.1.0         h59b6b97_46320
jpeg                      9e                   h2bbff1b_1
kiwisolver                1.4.4            py38hd77b12b_0
krb5                      1.20.1               h5b6d351_0
lerc                      3.0                  hd77b12b_0
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libclang                  14.0.6          default_hb5a9fac_1
libclang13                14.0.6          default_h8e68704_1
libdeflate                1.17                 h2bbff1b_1
libffi                    3.4.4                hd77b12b_0
libiconv                  1.16                 h2bbff1b_2
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.39               h8cc25b3_0
libpq                     12.15                h906ac69_1
libprotobuf               3.20.3               h23ce68f_0
libtiff                   4.5.1                hd77b12b_0
libuv                     1.44.2               h2bbff1b_0
libvorbis                 1.3.7                he774522_0
libwebp                   1.3.2                hbc33d0d_0
libwebp-base              1.3.2                h2bbff1b_0
libxml2                   2.10.4               h0ad7f3c_1
libxslt                   1.1.37               h2bbff1b_1
lz4-c                     1.9.4                h2bbff1b_0
matplotlib                3.5.3            py38haa244fe_2    conda-forge
matplotlib-base           3.5.3            py38hd77b12b_0
mkl                       2023.1.0         h6b88ed4_46358
mkl-service               2.4.0            py38h2bbff1b_1
mkl_fft                   1.3.8            py38h2bbff1b_0
mkl_random                1.2.4            py38h59b6b97_0
munkres                   1.1.4                      py_0
ninja                     1.10.2               haa95532_5
ninja-base                1.10.2               h6d14046_5
numpy                     1.24.3           py38h79a8e48_1
numpy-base                1.24.3           py38h8a87ada_1
opencv                    4.6.0            py38ha36de5b_5
openjpeg                  2.4.0                h4fc8c34_0
openssl                   3.0.12               h2bbff1b_0
packaging                 23.1             py38haa95532_0
pcre                      8.45                 hd77b12b_0
pillow                    10.0.1           py38h045eedc_0
pip                       23.3.1           py38haa95532_0
ply                       3.11                     py38_0
pyparsing                 3.0.9            py38haa95532_0
pyqt                      5.15.10          py38hd77b12b_0
pyqt5-sip                 12.13.0          py38h2bbff1b_0
python                    3.8.18               h1aa4202_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.10.0          py3.8_cuda11.3_cudnn8_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
qt-main                   5.15.2               h879a1e9_9
qt-webengine              5.15.9               h5bd16bc_7
qtwebkit                  5.212                h2bbfb41_5
setuptools                68.0.0           py38haa95532_0
sip                       6.7.12           py38hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.41.2               h2bbff1b_0
tbb                       2021.8.0             h59b6b97_0
tk                        8.6.12               h2bbff1b_0
tomli                     2.0.1            py38haa95532_0
torchaudio                0.10.0               py38_cu113    pytorch
torchvision               0.11.0               py38_cu113    pytorch
tornado                   6.3.3            py38h2bbff1b_0
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
typing_extensions         4.7.1            py38haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.41.2           py38haa95532_0
xz                        5.4.5                h8cc25b3_0
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.5                hd43e919_0
`

My computer configuration:
win10 GPU:3060

Looking forward to your suggestions!!

**Comment by LinWeiJeff** [comment]
> I have the same problems: `(AGE) D:\model\AGE-main>python tools/inference.py File "D:\model\AGE-main\.\models\stylegan2\op\fused_act.py", line 9, in <module> fused = load( File "D:\SourceCode\anaconda3\envs\AGE\lib\site-packages\torch\utils\cpp_extension.py", line 1124, in load return _jit_compile( File "D:\SourceCode\anaconda3\envs\AGE\lib\site-packages\torch\utils\cpp_extension.py", line 1362, in _jit_compile return _import_module_from_library(name, build_directory, is_python_module) File "D:\SourceCode\anaconda3\envs\AGE\lib\site-packages\torch\utils\cpp_extension.py", line 1752, in _import_module_from_library module = importlib.util.module_from_spec(spec) **ImportError: DLL load failed while importing fused: The specified module could not be found.**`
> 
> The packages I installed with conda are as follows: `# packages in environment at D:\SourceCode\anaconda3\envs\AGE:
> 
> # Name Version Build Channel
> blas 1.0 mkl brotli 1.0.9 h2bbff1b_7 brotli-bin 1.0.9 h2bbff1b_7 ca-certificates 2023.08.22 haa95532_0 certifi 2023.11.17 py38haa95532_0 colorama 0.4.6 py38haa95532_0 cudatoolkit 11.3.1 h280eb24_10 conda-forge cycler 0.11.0 pyhd3eb1b0_0 eigen 3.4.0 h59b6b97_0 ffmpeg 4.2.2 he774522_0 fonttools 4.25.0 pyhd3eb1b0_0 freetype 2.12.1 ha860e81_0 giflib 5.2.1 h8cc25b3_3 glib 2.69.1 h5dc1a3c_2 gst-plugins-base 1.18.5 h9e645db_0 gstreamer 1.18.5 hd78058f_0 hdf5 1.12.1 h51c971a_3 icc_rt 2022.1.0 h6049295_2 icu 58.2 ha925a31_3 intel-openmp 2023.1.0 h59b6b97_46320 jpeg 9e h2bbff1b_1 kiwisolver 1.4.4 py38hd77b12b_0 krb5 1.20.1 h5b6d351_0 lerc 3.0 hd77b12b_0 libbrotlicommon 1.0.9 h2bbff1b_7 libbrotlidec 1.0.9 h2bbff1b_7 libbrotlienc 1.0.9 h2bbff1b_7 libclang 14.0.6 default_hb5a9fac_1 libclang13 14.0.6 default_h8e68704_1 libdeflate 1.17 h2bbff1b_1 libffi 3.4.4 hd77b12b_0 libiconv 1.16 h2bbff1b_2 libogg 1.3.5 h2bbff1b_1 libpng 1.6.39 h8cc25b3_0 libpq 12.15 h906ac69_1 libprotobuf 3.20.3 h23ce68f_0 libtiff 4.5.1 hd77b12b_0 libuv 1.44.2 h2bbff1b_0 libvorbis 1.3.7 he774522_0 libwebp 1.3.2 hbc33d0d_0 libwebp-base 1.3.2 h2bbff1b_0 libxml2 2.10.4 h0ad7f3c_1 libxslt 1.1.37 h2bbff1b_1 lz4-c 1.9.4 h2bbff1b_0 matplotlib 3.5.3 py38haa244fe_2 conda-forge matplotlib-base 3.5.3 py38hd77b12b_0 mkl 2023.1.0 h6b88ed4_46358 mkl-service 2.4.0 py38h2bbff1b_1 mkl_fft 1.3.8 py38h2bbff1b_0 mkl_random 1.2.4 py38h59b6b97_0 munkres 1.1.4 py_0 ninja 1.10.2 haa95532_5 ninja-base 1.10.2 h6d14046_5 numpy 1.24.3 py38h79a8e48_1 numpy-base 1.24.3 py38h8a87ada_1 opencv 4.6.0 py38ha36de5b_5 openjpeg 2.4.0 h4fc8c34_0 openssl 3.0.12 h2bbff1b_0 packaging 23.1 py38haa95532_0 pcre 8.45 hd77b12b_0 pillow 10.0.1 py38h045eedc_0 pip 23.3.1 py38haa95532_0 ply 3.11 py38_0 pyparsing 3.0.9 py38haa95532_0 pyqt 5.15.10 py38hd77b12b_0 pyqt5-sip 12.13.0 py38h2bbff1b_0 python 3.8.18 h1aa4202_0 python-dateutil 2.8.2 pyhd3eb1b0_0 python_abi 3.8 2_cp38 conda-forge pytorch 1.10.0 py3.8_cuda11.3_cudnn8_0 pytorch pytorch-mutex 1.0 cuda pytorch qt-main 5.15.2 h879a1e9_9 qt-webengine 5.15.9 h5bd16bc_7 qtwebkit 5.212 h2bbfb41_5 setuptools 68.0.0 py38haa95532_0 sip 6.7.12 py38hd77b12b_0 six 1.16.0 pyhd3eb1b0_1 sqlite 3.41.2 h2bbff1b_0 tbb 2021.8.0 h59b6b97_0 tk 8.6.12 h2bbff1b_0 tomli 2.0.1 py38haa95532_0 torchaudio 0.10.0 py38_cu113 pytorch torchvision 0.11.0 py38_cu113 pytorch tornado 6.3.3 py38h2bbff1b_0 tqdm 4.66.1 pyhd8ed1ab_0 conda-forge typing_extensions 4.7.1 py38haa95532_0 vc 14.2 h21ff451_1 vs2015_runtime 14.27.29016 h5e58377_2 wheel 0.41.2 py38haa95532_0 xz 5.4.5 h8cc25b3_0 zlib 1.2.13 h8cc25b3_0 zstd 1.5.5 hd43e919_0 `
> 
> My computer configuration: win10 GPU:3060
> 
> Looking forward to your suggestions!!

@ATUI-TING Hello, I have a very similar problem as your problem you asked above, did you solve it?

**Comment by ATUI-TING** [comment]
> > I have the same problems: `(AGE) D:\model\AGE-main>python tools/inference.py File "D:\model\AGE-main\.\models\stylegan2\op\fused_act.py", line 9, in <module> fused = load( File "D:\SourceCode\anaconda3\envs\AGE\lib\site-packages\torch\utils\cpp_extension.py", line 1124, in load return _jit_compile( File "D:\SourceCode\anaconda3\envs\AGE\lib\site-packages\torch\utils\cpp_extension.py", line 1362, in _jit_compile return _import_module_from_library(name, build_directory, is_python_module) File "D:\SourceCode\anaconda3\envs\AGE\lib\site-packages\torch\utils\cpp_extension.py", line 1752, in _import_module_from_library module = importlib.util.module_from_spec(spec) **ImportError: DLL load failed while importing fused: The specified module could not be found.**`
> > The packages I installed with conda are as follows: `# packages in environment at D:\SourceCode\anaconda3\envs\AGE:
> > # Name Version Build Channel
> > blas 1.0 mkl brotli 1.0.9 h2bbff1b_7 brotli-bin 1.0.9 h2bbff1b_7 ca-certificates 2023.08.22 haa95532_0 certifi 2023.11.17 py38haa95532_0 colorama 0.4.6 py38haa95532_0 cudatoolkit 11.3.1 h280eb24_10 conda-forge cycler 0.11.0 pyhd3eb1b0_0 eigen 3.4.0 h59b6b97_0 ffmpeg 4.2.2 he774522_0 fonttools 4.25.0 pyhd3eb1b0_0 freetype 2.12.1 ha860e81_0 giflib 5.2.1 h8cc25b3_3 glib 2.69.1 h5dc1a3c_2 gst-plugins-base 1.18.5 h9e645db_0 gstreamer 1.18.5 hd78058f_0 hdf5 1.12.1 h51c971a_3 icc_rt 2022.1.0 h6049295_2 icu 58.2 ha925a31_3 intel-openmp 2023.1.0 h59b6b97_46320 jpeg 9e h2bbff1b_1 kiwisolver 1.4.4 py38hd77b12b_0 krb5 1.20.1 h5b6d351_0 lerc 3.0 hd77b12b_0 libbrotlicommon 1.0.9 h2bbff1b_7 libbrotlidec 1.0.9 h2bbff1b_7 libbrotlienc 1.0.9 h2bbff1b_7 libclang 14.0.6 default_hb5a9fac_1 libclang13 14.0.6 default_h8e68704_1 libdeflate 1.17 h2bbff1b_1 libffi 3.4.4 hd77b12b_0 libiconv 1.16 h2bbff1b_2 libogg 1.3.5 h2bbff1b_1 libpng 1.6.39 h8cc25b3_0 libpq 12.15 h906ac69_1 libprotobuf 3.20.3 h23ce68f_0 libtiff 4.5.1 hd77b12b_0 libuv 1.44.2 h2bbff1b_0 libvorbis 1.3.7 he774522_0 libwebp 1.3.2 hbc33d0d_0 libwebp-base 1.3.2 h2bbff1b_0 libxml2 2.10.4 h0ad7f3c_1 libxslt 1.1.37 h2bbff1b_1 lz4-c 1.9.4 h2bbff1b_0 matplotlib 3.5.3 py38haa244fe_2 conda-forge matplotlib-base 3.5.3 py38hd77b12b_0 mkl 2023.1.0 h6b88ed4_46358 mkl-service 2.4.0 py38h2bbff1b_1 mkl_fft 1.3.8 py38h2bbff1b_0 mkl_random 1.2.4 py38h59b6b97_0 munkres 1.1.4 py_0 ninja 1.10.2 haa95532_5 ninja-base 1.10.2 h6d14046_5 numpy 1.24.3 py38h79a8e48_1 numpy-base 1.24.3 py38h8a87ada_1 opencv 4.6.0 py38ha36de5b_5 openjpeg 2.4.0 h4fc8c34_0 openssl 3.0.12 h2bbff1b_0 packaging 23.1 py38haa95532_0 pcre 8.45 hd77b12b_0 pillow 10.0.1 py38h045eedc_0 pip 23.3.1 py38haa95532_0 ply 3.11 py38_0 pyparsing 3.0.9 py38haa95532_0 pyqt 5.15.10 py38hd77b12b_0 pyqt5-sip 12.13.0 py38h2bbff1b_0 python 3.8.18 h1aa4202_0 python-dateutil 2.8.2 pyhd3eb1b0_0 python_abi 3.8 2_cp38 conda-forge pytorch 1.10.0 py3.8_cuda11.3_cudnn8_0 pytorch pytorch-mutex 1.0 cuda pytorch qt-main 5.15.2 h879a1e9_9 qt-webengine 5.15.9 h5bd16bc_7 qtwebkit 5.212 h2bbfb41_5 setuptools 68.0.0 py38haa95532_0 sip 6.7.12 py38hd77b12b_0 six 1.16.0 pyhd3eb1b0_1 sqlite 3.41.2 h2bbff1b_0 tbb 2021.8.0 h59b6b97_0 tk 8.6.12 h2bbff1b_0 tomli 2.0.1 py38haa95532_0 torchaudio 0.10.0 py38_cu113 pytorch torchvision 0.11.0 py38_cu113 pytorch tornado 6.3.3 py38h2bbff1b_0 tqdm 4.66.1 pyhd8ed1ab_0 conda-forge typing_extensions 4.7.1 py38haa95532_0 vc 14.2 h21ff451_1 vs2015_runtime 14.27.29016 h5e58377_2 wheel 0.41.2 py38haa95532_0 xz 5.4.5 h8cc25b3_0 zlib 1.2.13 h8cc25b3_0 zstd 1.5.5 hd43e919_0 `
> > My computer configuration: win10 GPU:3060
> > Looking forward to your suggestions!!
> 
> @ATUI-TING Hello, I have a very similar problem as your problem you asked above, did you solve it?

Yes, U can try to download VS2019.
Or try modifying the CUDA HOME to correspond to your CUDA.

**Comment by LinWeiJeff** [comment]
> > > I have the same problems: `(AGE) D:\model\AGE-main>python tools/inference.py File "D:\model\AGE-main\.\models\stylegan2\op\fused_act.py", line 9, in <module> fused = load( File "D:\SourceCode\anaconda3\envs\AGE\lib\site-packages\torch\utils\cpp_extension.py", line 1124, in load return _jit_compile( File "D:\SourceCode\anaconda3\envs\AGE\lib\site-packages\torch\utils\cpp_extension.py", line 1362, in _jit_compile return _import_module_from_library(name, build_directory, is_python_module) File "D:\SourceCode\anaconda3\envs\AGE\lib\site-packages\torch\utils\cpp_extension.py", line 1752, in _import_module_from_library module = importlib.util.module_from_spec(spec) **ImportError: DLL load failed while importing fused: The specified module could not be found.**`
> > > The packages I installed with conda are as follows: `# packages in environment at D:\SourceCode\anaconda3\envs\AGE:
> > > # Name Version Build Channel
> > > blas 1.0 mkl brotli 1.0.9 h2bbff1b_7 brotli-bin 1.0.9 h2bbff1b_7 ca-certificates 2023.08.22 haa95532_0 certifi 2023.11.17 py38haa95532_0 colorama 0.4.6 py38haa95532_0 cudatoolkit 11.3.1 h280eb24_10 conda-forge cycler 0.11.0 pyhd3eb1b0_0 eigen 3.4.0 h59b6b97_0 ffmpeg 4.2.2 he774522_0 fonttools 4.25.0 pyhd3eb1b0_0 freetype 2.12.1 ha860e81_0 giflib 5.2.1 h8cc25b3_3 glib 2.69.1 h5dc1a3c_2 gst-plugins-base 1.18.5 h9e645db_0 gstreamer 1.18.5 hd78058f_0 hdf5 1.12.1 h51c971a_3 icc_rt 2022.1.0 h6049295_2 icu 58.2 ha925a31_3 intel-openmp 2023.1.0 h59b6b97_46320 jpeg 9e h2bbff1b_1 kiwisolver 1.4.4 py38hd77b12b_0 krb5 1.20.1 h5b6d351_0 lerc 3.0 hd77b12b_0 libbrotlicommon 1.0.9 h2bbff1b_7 libbrotlidec 1.0.9 h2bbff1b_7 libbrotlienc 1.0.9 h2bbff1b_7 libclang 14.0.6 default_hb5a9fac_1 libclang13 14.0.6 default_h8e68704_1 libdeflate 1.17 h2bbff1b_1 libffi 3.4.4 hd77b12b_0 libiconv 1.16 h2bbff1b_2 libogg 1.3.5 h2bbff1b_1 libpng 1.6.39 h8cc25b3_0 libpq 12.15 h906ac69_1 libprotobuf 3.20.3 h23ce68f_0 libtiff 4.5.1 hd77b12b_0 libuv 1.44.2 h2bbff1b_0 libvorbis 1.3.7 he774522_0 libwebp 1.3.2 hbc33d0d_0 libwebp-base 1.3.2 h2bbff1b_0 libxml2 2.10.4 h0ad7f3c_1 libxslt 1.1.37 h2bbff1b_1 lz4-c 1.9.4 h2bbff1b_0 matplotlib 3.5.3 py38haa244fe_2 conda-forge matplotlib-base 3.5.3 py38hd77b12b_0 mkl 2023.1.0 h6b88ed4_46358 mkl-service 2.4.0 py38h2bbff1b_1 mkl_fft 1.3.8 py38h2bbff1b_0 mkl_random 1.2.4 py38h59b6b97_0 munkres 1.1.4 py_0 ninja 1.10.2 haa95532_5 ninja-base 1.10.2 h6d14046_5 numpy 1.24.3 py38h79a8e48_1 numpy-base 1.24.3 py38h8a87ada_1 opencv 4.6.0 py38ha36de5b_5 openjpeg 2.4.0 h4fc8c34_0 openssl 3.0.12 h2bbff1b_0 packaging 23.1 py38haa95532_0 pcre 8.45 hd77b12b_0 pillow 10.0.1 py38h045eedc_0 pip 23.3.1 py38haa95532_0 ply 3.11 py38_0 pyparsing 3.0.9 py38haa95532_0 pyqt 5.15.10 py38hd77b12b_0 pyqt5-sip 12.13.0 py38h2bbff1b_0 python 3.8.18 h1aa4202_0 python-dateutil 2.8.2 pyhd3eb1b0_0 python_abi 3.8 2_cp38 conda-forge pytorch 1.10.0 py3.8_cuda11.3_cudnn8_0 pytorch pytorch-mutex 1.0 cuda pytorch qt-main 5.15.2 h879a1e9_9 qt-webengine 5.15.9 h5bd16bc_7 qtwebkit 5.212 h2bbfb41_5 setuptools 68.0.0 py38haa95532_0 sip 6.7.12 py38hd77b12b_0 six 1.16.0 pyhd3eb1b0_1 sqlite 3.41.2 h2bbff1b_0 tbb 2021.8.0 h59b6b97_0 tk 8.6.12 h2bbff1b_0 tomli 2.0.1 py38haa95532_0 torchaudio 0.10.0 py38_cu113 pytorch torchvision 0.11.0 py38_cu113 pytorch tornado 6.3.3 py38h2bbff1b_0 tqdm 4.66.1 pyhd8ed1ab_0 conda-forge typing_extensions 4.7.1 py38haa95532_0 vc 14.2 h21ff451_1 vs2015_runtime 14.27.29016 h5e58377_2 wheel 0.41.2 py38haa95532_0 xz 5.4.5 h8cc25b3_0 zlib 1.2.13 h8cc25b3_0 zstd 1.5.5 hd43e919_0 `
> > > My computer configuration: win10 GPU:3060
> > > Looking forward to your suggestions!!
> > 
> > 
> > @ATUI-TING Hello, I have a very similar problem as your problem you asked above, did you solve it?
> 
> Yes, U can try to download VS2019. Or try modifying the CUDA HOME to correspond to your CUDA.

@ATUI-TING Thanks for your replying!
I have installed VS2022 (Visual Studio 2022 Community) instead of VS2019, does VS2022 work?
In addition, if I want to modify CUDA HOME, does it mean I can directly use command:`set CUDA_HOME=11.3.1` (my cudatoolkit version is 11.3.1) in anaconda virtual environment on Windows cmd?

The picture shown as below shows the libs and their versions installed:
![messageImage_1702959222963](https://github.com/OpenGVLab/DragGAN/assets/152743957/a84d9322-b0d2-48c5-a1b9-95ca2a1fef59)

**Comment by LinWeiJeff** [comment]
@ATUI-TING I have tried to set environment variable `CUDA_HOME` to **C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2** (as shown as the first picture below, I installed my cuda in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2), after setting the environment variable `CUDA_HOME` and then I reopen cmd. Unfortunately, the error still appeared.
How should I do to solve it?
Thanks!

![messageImage_1702978294919](https://github.com/OpenGVLab/DragGAN/assets/152743957/98eb7901-3db7-4d73-b23b-ac957c8438dd)

The following picture shows the error message, and the Chinese in the last line is "The specified module could not be found."
![messageImage_1702979158423](https://github.com/OpenGVLab/DragGAN/assets/152743957/361a218f-a103-4443-a0f5-d5f20b8f0ce8)
