### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by astatonn** [Zeqiang-Lai/DragGAN#51]
Hi, I'm trying to run DragGAN but I got this message error:

`To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\Lucas Lima\miniconda3\envs\draggan\lib\site-packages\gradio\routes.py", line 406, in run_predict
    event_data=event_data,
  File "C:\Users\Lucas Lima\miniconda3\envs\draggan\lib\site-packages\gradio\blocks.py", line 1300, in process_api
    fn_index, inputs, iterator, request, event_id, event_data
  File "C:\Users\Lucas Lima\miniconda3\envs\draggan\lib\site-packages\gradio\blocks.py", line 1037, in call_function
    utils.async_iteration, iterator, limiter=self.limiter
  File "C:\Users\Lucas Lima\miniconda3\envs\draggan\lib\site-packages\anyio\to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "C:\Users\Lucas Lima\miniconda3\envs\draggan\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Lucas Lima\miniconda3\envs\draggan\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Lucas Lima\miniconda3\envs\draggan\lib\site-packages\gradio\utils.py", line 488, in async_iteration
    return next(iterator)
  File "C:\Users\Lucas Lima\miniconda3\envs\draggan\lib\site-packages\draggan\web.py", line 135, in on_drag
    max_iters=max_iters):
  File "C:\Users\Lucas Lima\miniconda3\envs\draggan\lib\site-packages\draggan\api.py", line 191, in drag_gan
    for qi in neighbor(int(pi[0]), int(pi[1]), r1):
  File "C:\Users\Lucas Lima\miniconda3\envs\draggan\lib\site-packages\draggan\api.py", line 171, in neighbor
    points.append(torch.tensor([i, j]).float().cuda())
  File "C:\Users\Lucas Lima\miniconda3\envs\draggan\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled`

I have AMD Radeon RX 590
Does anyone knows what about it?

**Comment by Zeqiang-Lai** [comment]
PyTorch only support AMD GPU on Linux.
Check this out if you are using linux. https://pytorch.org/get-started/locally/

<img width="932" alt="image" src="https://github.com/Zeqiang-Lai/DragGAN/assets/26198430/734bc8c7-6e8d-447a-93c7-f485c9082c71">

Otherwise, you could use CPU mode
```
python -m draggan.web --device cpu
```

**Comment by f-izzat** [comment]
@Zeqiang-Lai I still get the same error as the original post even when running wih CPU mode

**Comment by astatonn** [comment]
@Zeqiang-Lai I still get error even running with cpu mode.

**Comment by ElvisWangTech** [comment]
I pulled the latest code and found that line 207 of draggan.py is also hardcoded。
`device = torch.device("cuda")`

**Comment by ShifterXD** [comment]
did he fix the bag wish cuda?
