### ISSUE TITLE
'NoneType' object has no attribute 'rsplit' 

### ISSUE THREAD

**Issue by chenzx2** [Zeqiang-Lai/DragGAN#54]
Traceback (most recent call last):
  File "D:\python\ws\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\python\ws\venv\lib\site-packages\gradio\blocks.py", line 1313, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\python\ws\venv\lib\site-packages\gradio\blocks.py", line 1163, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "D:/python/ws/venv/code/DragGAN-main/gradio_app.py", line 73, in preprocess
    return super().preprocess(x)
  File "D:\python\ws\venv\lib\site-packages\gradio\components.py", line 1795, in preprocess
    mask_im = processing_utils.decode_base64_to_image(mask)
  File "D:\python\ws\venv\lib\site-packages\gradio\processing_utils.py", line 50, in decode_base64_to_image
    image_encoded = extract_base64_data(encoding)
  File "D:\python\ws\venv\lib\site-packages\gradio\processing_utils.py", line 41, in extract_base64_data
    return x.rsplit(",", 1)[-1]
AttributeError: 'NoneType' object has no attribute 'rsplit'

**Comment by Zeqiang-Lai** [comment]
Did you upload custom image from Draw mask pannel ? You should upload custom image from select handle points pannel.

**Comment by VCBE123** [comment]
> Did you upload custom image from Draw mask pannel ? You should upload custom image from select handle points pannel.

yes

**Comment by chenbinghui1** [comment]
> Did you upload custom image from Draw mask pannel ? You should upload custom image from select handle points pannel.

It doesn't work.  and the error log is as follows:
![image](https://github.com/Zeqiang-Lai/DragGAN/assets/11517207/6ca6e6c2-490d-4ed1-a293-9a770190aa57)
![image](https://github.com/Zeqiang-Lai/DragGAN/assets/11517207/b374325c-3248-4863-ac08-e7319f7ac6d3)

do you know what happens?
