### ISSUE TITLE
[Bug Fixed] RuntimeError: Ninja is required to load C++ extensions

### ISSUE THREAD

**Issue by kanseaveg** [Zeqiang-Lai/DragGAN#6]
```
(pytorch) [cyy@localhost draggan]$ python gradio_app.py
Traceback (most recent call last):
  File "/code/draggan/gradio_app.py", line 6, in <module>
    from drag_gan import drag_gan, stylegan2
  File "/code/draggan/drag_gan.py", line 12, in <module>
    from stylegan2.model import Generator
  File "/code/draggan/stylegan2/model.py", line 8, in <module>
    from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d, conv2d_gradfix
  File "/code/draggan/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/code/draggan/stylegan2/op/fused_act.py", line 11, in <module>
    fused = load(
  File "anaconda/envs/pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "/env/anaconda/envs/pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1357, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/env/anaconda/envs/pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1438, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "/env/anaconda/envs/pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1494, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions
```

**Comment by Zeqiang-Lai** [comment]
You could try `pip install ninja`

**Comment by kanseaveg** [comment]
For Ubuntu/Debian：
```
sudo apt-get install ninja-build
```
For Fedora/CentOS/RHEL：
```
sudo dnf install ninja-build
```
For macOS：
```
brew install ninja
```
For Windows：
```
choco install ninja
```

**Comment by kanseaveg** [comment]
> You could try `pip install ninja`你可以试试 `pip install ninja`

thanks, i try the ``` yum -y install ninja-build`` and it works.

**Comment by wtjiang98** [comment]
> > You could try `pip install ninja`你可以试试 `pip install ninja`
> 
> thanks, i try the ``` yum -y install ninja-build`` and it works.

Works for me in my Fedora server. Thanks!
