### ISSUE TITLE
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA 

### ISSUE THREAD

**Issue by jiyuwangbupt** [Zeqiang-Lai/DragGAN#61]
![image](https://github.com/Zeqiang-Lai/DragGAN/assets/37127150/5973ba3e-cf5b-4498-bd67-96620478ba0c)

**Comment by Zeqiang-Lai** [comment]
Note for Colab, remember to select a GPU via Runtime/Change runtime type (代码执行程序/更改运行时类型).

**Comment by adrianmikula** [comment]
This error is hidden in the console output, but the web GUI doesn't tell the user that it's a GPU driver issue.  Please make the GUI error display a more detailed error message.

My console output:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gradio/routes.py", line 406, in run_predict
    event_data=event_data,
  File "/usr/local/lib/python3.7/site-packages/gradio/blocks.py", line 1300, in process_api
    fn_index, inputs, iterator, request, event_id, event_data
  File "/usr/local/lib/python3.7/site-packages/gradio/blocks.py", line 1023, in call_function
    fn, *processed_input, limiter=self.limiter
  File "/usr/local/lib/python3.7/site-packages/anyio/to_thread.py", line 34, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/draggan/web.py", line 224, in on_image_change
    image_size=image_size
  File "/app/draggan/stylegan2/inversion.py", line 113, in inverse_image
    imgs = torch.stack(imgs, 0).to(device)
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
