### ISSUE TITLE
 connection reset by peer

### ISSUE THREAD

**Issue by YuzhouPeng** [Zeqiang-Lai/DragGAN#68]
After I installed the requirements.txt and run gradio app, I got following error

raceback (most recent call last):
  File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 1426, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gemini/code/DragGAN/gradio_app.py", line 346, in <module>
    demo = main()
  File "/gemini/code/DragGAN/gradio_app.py", line 241, in main
    wrapped_model = ModelWrapper(ckpt=DEFAULT_CKPT, size=CKPT_SIZE[DEFAULT_CKPT])
  File "/gemini/code/DragGAN/gradio_app.py", line 78, in __init__
    self.g_ema = stylegan2(**kwargs).to(device)
  File "/gemini/code/DragGAN/drag_gan.py", line 126, in stylegan2
    checkpoint = torch.load(get_path(ckpt))
  File "/gemini/code/DragGAN/drag_gan.py", line 31, in get_path
    download_url(url, save_path)
  File "/gemini/code/DragGAN/drag_gan.py", line 39, in download_url
    urllib.request.urlretrieve(url, filename=output_path, reporthook=t.update_to)
  File "/usr/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

How can I solve this problem? Thank you

**Comment by JYF98** [comment]
Download the .pt files manually and put it in '/checkpoints'

**Comment by YuzhouPeng** [comment]
thank you!

**Comment by Aricling** [comment]
I'm using the gradio to automate the download process, and don't want to manually download it. In this circumstance, I still get this error. How can I solve the 'Connection reset by peer' problem?
