### ISSUE TITLE
[Bug] IndexError: index 508 is out of bounds for dimension 2 with size 256

### ISSUE THREAD

**Issue by kanseaveg** [Zeqiang-Lai/DragGAN#8]
I just put the photo below:
![1](https://github.com/Zeqiang-Lai/DragGAN/assets/80022154/c9780ee7-d080-48ed-89ef-c9ea6e4a2b9b)

I tried to open the mouth of the kitten.  And select the second one: the cat style gan.
![image](https://github.com/Zeqiang-Lai/DragGAN/assets/80022154/9d4a11fc-5ee4-44c2-8586-5a08ada3c613)

It reports the bug below:
![image](https://github.com/Zeqiang-Lai/DragGAN/assets/80022154/9fa4a89e-5516-4f7f-913f-226cbac0d70f)

how to fix it ? thank you?

**Comment by kanseaveg** [comment]
Another bug is 
```
/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/torch/nn/functional.py:3063: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/gradio/routes.py", line 421, in run_predict
    event_data=event_data,
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/gradio/blocks.py", line 1321, in process_api
    fn_index, inputs, iterator, request, event_id, event_data
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/gradio/blocks.py", line 1064, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/gradio/utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/gradio/utils.py", line 508, in __anext__
    run_sync_iterator_async, self.iterator, limiter=self.limiter
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread    return await future
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/gradio/utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "gradio_app.py", line 103, in on_drag
    max_iters=max_iters):
  File "/home/amax/euan/code/draggan/drag_gan.py", line 193, in drag_gan
    f1 = bilinear_interpolate_torch(F2, qi[0], qi[1]).detach()
  File "/home/amax/euan/code/draggan/drag_gan.py", line 153, in bilinear_interpolate_torch
    Ia = im[:, :, y0, x0]
IndexError: index 508 is out of bounds for dimension 2 with size 256
/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/torch/nn/functional.py:3063: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/gradio/routes.py", line 421, in run_predict
    event_data=event_data,
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/gradio/blocks.py", line 1321, in process_api
    fn_index, inputs, iterator, request, event_id, event_data
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/gradio/blocks.py", line 1064, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/gradio/utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/gradio/utils.py", line 508, in __anext__
    run_sync_iterator_async, self.iterator, limiter=self.limiter
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread    return await future
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/amax/miniconda3/envs/cyy/lib/python3.7/site-packages/gradio/utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "gradio_app.py", line 103, in on_drag
    max_iters=max_iters):
  File "/home/amax/euan/code/draggan/drag_gan.py", line 197, in drag_gan
    loss += ((F2 - F0) * (1 - mask)).abs().mean() * lam
RuntimeError: The size of tensor a (1024) must match the size of tensor b (960) at non-singleton dimension 3
```

I think there's problem on uploading a image and drag the photo.

**Comment by Zeqiang-Lai** [comment]
This is a known issue, https://github.com/Zeqiang-Lai/DragGAN/issues/4 

We need some time to support it.
