### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7

### ISSUE THREAD

**Issue by santaonholidays** [Zeqiang-Lai/DragGAN#87]
F:\Draggan\DragGAN> python gradio_app.py
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
F:\Draggan\DragGAN\stylegan2\op\fused_act.py:22: UserWarning: (This is not error) Switch to native implementation
  warnings.warn(
F:\Draggan\DragGAN\stylegan2\op\upfirdn2d.py:21: UserWarning: (This is not error) Switch to native implementation
  warnings.warn(
Traceback (most recent call last):
  File "F:\Draggan\DragGAN\gradio_app.py", line 100, in <module>
    def on_click(image, target_point, points, size, evt: gr.SelectData):
AttributeError: module 'gradio' has no attribute 'SelectData'

Please help c:

**Comment by Zeqiang-Lai** [comment]
pip install gradio==3.28.1

**Comment by rperdon** [comment]
Getting the similar problem. 

No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
Traceback (most recent call last):
  File "C:\Users\Slade\Downloads\draggan_install\DragGAN\visualizer_drag.py", line 403, in <module>
    main()
  File "C:\Python\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Slade\Downloads\draggan_install\DragGAN\visualizer_drag.py", line 397, in main
    viz.draw_frame()
  File "C:\Users\Slade\Downloads\draggan_install\DragGAN\visualizer_drag.py", line 168, in draw_frame
    self._async_renderer.set_args(**self.args)
  File "C:\Users\Slade\Downloads\draggan_install\DragGAN\visualizer_drag.py", line 295, in set_args
    self._set_args_sync(**args)
  File "C:\Users\Slade\Downloads\draggan_install\DragGAN\visualizer_drag.py", line 312, in _set_args_sync
    self._renderer_obj = renderer.Renderer()
                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Slade\Downloads\draggan_install\DragGAN\viz\renderer.py", line 80, in __init__
    self._start_event   = torch.cuda.Event(enable_timing=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\torch\cuda\streams.py", line 164, in __new__
    return super(Event, cls).__new__(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\torch\cuda\_utils.py", line 46, in err_fn
    raise RuntimeError(
RuntimeError: Tried to instantiate dummy base class Event

**Comment by ltnlez** [comment]
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2'
Traceback (most recent call last):
  File "D:\dragondan\DragGAN\visualizer_drag.py", line 403, in <module>
    main()
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\dragondan\DragGAN\visualizer_drag.py", line 397, in main
    viz.draw_frame()
  File "D:\dragondan\DragGAN\visualizer_drag.py", line 168, in draw_frame
    self._async_renderer.set_args(**self.args)
  File "D:\dragondan\DragGAN\visualizer_drag.py", line 295, in set_args
    self._set_args_sync(**args)
  File "D:\dragondan\DragGAN\visualizer_drag.py", line 312, in _set_args_sync
    self._renderer_obj = renderer.Renderer()
  File "D:\dragondan\DragGAN\viz\renderer.py", line 80, in __init__
    self._start_event   = torch.cuda.Event(enable_timing=True)
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\streams.py", line 164, in __new__
    return super(Event, cls).__new__(
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\_utils.py", line 46, in err_fn
    raise RuntimeError(
RuntimeError: Tried to instantiate dummy base class Event

I have this problem, has anyone encountered it?

**Comment by SKVhacks** [comment]
me to sample problem
