### ISSUE TITLE
[BUG] It says AssertionError

### ISSUE THREAD

**Issue by tjhshiwo** [Zeqiang-Lai/DragGAN#93]
I used docker image to run the app and it showed error in the webpage after running the container:

error page:
![image](https://github.com/Zeqiang-Lai/DragGAN/assets/26499684/d6fc6317-30e1-443e-b59b-0c5fac389c5b)

trace log of the container:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gradio/routes.py", line 406, in run_predict
    event_data=event_data,
  File "/usr/local/lib/python3.7/site-packages/gradio/blocks.py", line 1297, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/usr/local/lib/python3.7/site-packages/gradio/blocks.py", line 1145, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/usr/local/lib/python3.7/site-packages/gradio/components.py", line 1780, in preprocess
    assert isinstance(x, dict)
AssertionError

**Comment by Zeqiang-Lai** [comment]
Not sure what the problem it is now, but refresh or restart the app may help.
